import { ApiManifest, EndpointDef } from '../../types';
import { composeDef } from './composeDef';
import configManager from '../managers/configManager';

/**
 * Generate api manifest.
 * @param inputDefs
 * @param baseUri
 */
export function generateManifest(inputDefs: EndpointDef[], baseUri: string): ApiManifest {
  const config = configManager.getConfig();

  const defs: EndpointDef[] = [];
  for (let def of inputDefs) {
    defs.push(composeDef(def, true));
  }

  return {
    baseUri,
    title: config.api.title ?? 'API Docs (generated by Defapi)',
    defaultHeaders: config.api.defaultHeaders,
    endpoints: defs
  };
}
